listen: localhost:9293
host: 0.0.0.0
port: 5050
data.dir: /foo
metadata.cache.max.age: 1m

batch.max:
  messages: 10
  time: 1s

logging:
  level: debug
  recovery: true
  raft: true
  nats: true

streams:
  retention.max:
    bytes: 1024
    messages: 100
    age: 1h
  cleaner.interval: 1m
  segment.max:
    bytes: 64
    age: 1m
  compact: 
    enabled: true
    max.goroutines: 2

clustering:
  server.id: foo
  namespace: bar
  raft:
    snapshot:
      retain: 10
      threshold: 100
    cache.size: 5
    bootstrap.peers:
      - a
      - b
  replica:
    max:
      lag.time: 1m
      leader.timeout: 30s
      idle.wait: 2s
    fetch.timeout: 3s
  min.insync.replicas: '1'
  replication.max.bytes: 1024

activity.stream:
  enabled: true
  publish.timeout: 1m
  publish.ack.policy: leader

nats:
  embedded: true
  embedded.config: nats.conf
  servers:
    - nats://localhost:4222
  user: user
  password: pass

cursors:
  stream:
    partitions: 2
    replication.factor: 3
    auto.pause.time: 1m

groups:
  consumer.timeout: 1m
  coordinator.timeout: 2m
